SELECT RATES.price, DEST_CODE.CODE FROM CDR
JOIN oper_ip on CDR.SRC_IP = oper_ip.IP_OP
JOIN SITE on SITE.ID = oper_ip.OP_ID
JOIN RATES on RATES.RATE_ID = SITE.rate_o
JOIN DEST_CODE on DEST_CODE.DEST_ID = RATES.CODE_ID
-- WHERE oper_ip.IP_OP = '92.42.108.210'
LIMIT 10