
version: '3.1'

services:

  db:
    image: mysql:8.0.16
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: voip
      MYSQL_PASSWORD: voip
      MYSQL_DATABASE: voip
      MYSQL_ROOT_PASSWORD: voip
    ports:
      - 3333:3306
    volumes:
    - ../voip.sql.gz:/docker-entrypoint-initdb.d/0_voip.sql.gz
    - ./data:/var/lib/mysql
